controllers/AgentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Agent;
use app\models\AgentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\libraries\Encryption;
use yii\filters\AccessControl;
/**
 * AgentController implements the CRUD actions for Agent model.
 */
class AgentController extends Controller
{
    /**
     * {@inheritdoc}
     */
     public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['agentIndex'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reset-pin'],
                        'roles' => ['agentResetPin'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Agent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AgentSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionResetPin($id) {
        $model = $this->findModel($id);
        $password = rand(1000, 9999);

            
        $model->salt = Encryption::generateSalt();
        $model->status = 3;
        if ($model->validate()) {
   
            $model->password = Encryption::encrypt($password, $model->salt);
            
            if ($model->save()) {
         
                 $sql = "INSERT INTO dbqueue (Originator, Destination, Message, SMSCID, MessageDirection) 
                            VALUES ('" . Yii::$app->params['originator'] . "', '" 
                            . $model->msisdn . "', '" . sprintf(Yii::$app->params['message'], $model->agent_name, $password) . "', 'SAFCOMKE', 'OUT')";
                \Yii::$app->db->createCommand($sql)->execute();
                Yii::$app->session->setFlash('info', 'Password has been changed. SMS has been sent to the agents number with their one time PIN');        
               
                
            }
        }
        $model->password = "";
        return $this->render('view', [
            'model' => $model,
        ]);
    }


    /**
     * Finds the Agent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Agent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Agent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserService;
use app\models\UserSearch;
use app\models\UserDetails;
use app\models\Educations;
use app\models\Qualifications;
use app\models\Companies;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\libraries\Encryption;
use yii\filters\AccessControl;
use \yii\web\UploadedFile;

use yii\helpers\Url;


/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['userIndex'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['userView'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['userCreate'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update'],
                        'roles' => ['userUpdate'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['change-password'],
                        'roles' => ['userChangePassword'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reset-account'],
                        'roles' => ['userResetAccount'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['account'],
                        'roles' => ['userAccount'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['download'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }



    public function actionChangePassword() {
        $model = $this->findModel(Yii::$app->user->id);
        
        if ($model->load(Yii::$app->request->post())) {
            $model->current_password = $_POST['User']['current_password'];
            $model->scenario = User::SCENARIO_CHANGEPASSWORD;
            if ($model->validate()) {
                if ($model->validatePassword($model->current_password, 
                        Yii::$app->user->identity->password, 
                        Yii::$app->user->identity->salt)) {
                    $user = User::findOne(Yii::$app->user->identity->id); 
                    if ($user) {
                        $user->salt = Encryption::generateSalt();  
                        $user->password =  Encryption::encrypt($model->password, $user->salt);
                        if ($user->update(false)) {
                            Yii::$app->user->logout();
        		    return $this->goHome();
                        }
                    } 
                } else {
                    
                    $model->addError("current_password", 
                            "You have entered an incorrect current password");
                }
            }
        }
        $model->current_password = "";
        $model->password = "";
        $model->repeat_password = "";
        return $this->render('change-password', [
                    'model' => $model,
        ]);
    }


    /*public function actionResetAccount($id) {
        $model = $this->findModel($id);
        $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
        if ($model->update()) {
            $content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                    . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td><a href=" 
                    . Url::toRoute(['site/reset', 'username' => $model->username, 
                    'key' => $model->activation_key], true) 
                    . ">Click here to activate your account</a></td></tr></table>" 
                    . "<p>This email is  auto-generated by Betamasano system. Do not reply.</p>";
            Yii::$app->mailer->compose('template', [
                        'content' => $content
                    ]) // a view rendering result becomes the message body here
                    ->setFrom(Yii::$app->params['sent_from'])
                    ->setTo($model->email)
                    ->setSubject('Credentials - Betamasano')
                    ->send();
            Yii::$app->session->setFlash('info', 'User Account reset succcess. A link has been sent to the users email');        
        
        } else {
            Yii::$app->session->setFlash('error', 'Error resetting user account');
        }
        return $this->redirect(['user/index']);
    }*/

    public function actionResetAccount($id) {
        $model = $this->findModel($id);
    
        if ($model->load(Yii::$app->request->post()) ) {
 
            $model->modified_by = Yii::$app->user->identity->id;
            $model->salt = Encryption::generateSalt();
            $model->status_id = User::STATUS_ACTIVE;
            $model->scenario = User::SCENARIO_RESET;
            if ($model->validate()) {
                $password = $model->password;
                $model->password = Encryption::encrypt($model->password, $model->salt);
                $model->repeat_password = $model->password;
                $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
                
                if ($model->save()) {
                    
                    /*
                    //Send EMail with credentials
                    $content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                                . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td><a href=" 
				. Url::toRoute(['site/activate', 'email' => $model->email, 'key' => $model->activation_key], true) 
				. ">Click here to activate your account</a></td></tr></table>" 
				. "<p>username : " . $model->username . "</p>"
                                . "<p>password : " . $password . "</p>"
                                . "<p>This email is  auto-generated by Betamasano system. Do not reply.</p>";
                    	    Yii::$app->mailer->compose('template', [
                                'content' => $content
                            ]) // a view rendering result becomes the message body here
                            ->setFrom(Yii::$app->params['sent_from'])
                            ->setTo($model->email)
                            ->setSubject('Credentials - Betamasano')
                            ->send();*/
                    Yii::$app->session->setFlash('info', 'Password has been changed. An email has been sent to the account with the new information');        
                   
                    
                }
            }
        }
        $model->password = "";
        $model->repeat_password = "";
        return $this->render('reset', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new User();
    
        if ($model->load(Yii::$app->request->post()) ) {

            $model->created_by = Yii::$app->user->identity->id;
            $model->salt = Encryption::generateSalt();
            $model->status_id = User::STATUS_ACTIVE;
            $model->scenario = User::SCENARIO_CREATE;

            if ($model->validate()) {
                $password = $model->password;
                $model->password = Encryption::encrypt($model->password, $model->salt);
                $model->repeat_password = $model->password;
                $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
                $model->msisdn = "254" . substr($model->msisdn, -9);
                if ($model->save()) {
                    
                    
                    $auth = Yii::$app->authManager;
                    switch ($model->role_id) {
                        case 1:
                            $role =  $auth->getRole('super_admin');
                        break;
                        case 2:
                            $role =  $auth->getRole('ccr');
                        break;
                    }
                        
                    $auth->assign($role, $model->getId()); 
                        
                    //Send EMail with credentials
                    /*$content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                                . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td>
                                     <a href=" . Url::toRoute(['site/activate', 'email' => $model->email, 
                                'key' => $model->activation_key], true) . ">Click here to activate your account</a></td>
                                </tr></table>" 
                            . "<p>username : " . $model->username . "</p>"
                            . "<p>password : " . $password . "</p>"
                            . "<p>This email is  auto-generated by DASSO system. Do not reply.</p>";

views/layouts/main.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;

$bundle = yiister\gentelella\assets\Asset::register($this);


?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>" >
<?php $this->beginBody(); ?>
<div class="container body">

    <div class="main_container">

        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">

                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Betamasano Portal!</span></a>
                </div>
                <div class="clearfix"></div>
                <?php Yii::$app->user->isGuest ?"":
                    '<div class="profile">
                        <div class="profile_pic">
                            <img src="http://placehold.it/128x128" alt="..." class="img-circle profile_img">
                        </div>

                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>' . Yii::$app->user->identity->username .'</h2>
                        </div>
                    </div>'
                    ?>
                <!-- /menu prile quick info -->

                <br />

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                    <div class="menu_section">
                        <h3>Betamasano</h3>
                        <?=
                        \yiister\gentelella\widgets\Menu::widget(
                            [
                                "items" => [
                                    
                                    [
                                        "label" => "Agents",
                                        "url" => ["agent/index"],
                                        "icon" => "cog",
                                        'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('agentIndex'):0
                                       
                                    ],
                                    [
                                        "label" => "Users",
                                        "url" => "#",
                                        "icon" => "user",
                                        "items" => [
                                            [
                                                "label" => "All Users",
                                                "url" => ["user/index"],
                                                'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('userIndex'):0
                                            ],
                                            [
                                                "label" => "New User",
                                                "url" => ["user/create"],
                                                'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('userCreate'):0
                                            ],
                                            [
                                                "label" => "Change Password",
                                                "url" => ["user/change-password"],
                                                'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('userChangePassword'):0
                                            ],
                                           
                                        ],
                                        'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('user'):0
                                    ],
                                    [
                                        "label" => "Audit Trails",
                                        "url" => ["audit"],
                                        "icon" => "info",
                                        'visible' => (!Yii::$app->user->isGuest)?\Yii::$app->user->can('accessLogIndex'):0
                                    ],
                                ],
                            ]
                        );
                        ?>
                    </div>

                </div>
                <!-- /sidebar menu -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            
        <?php
            NavBar::begin([
                    //'brandLabel' => '', 
                    'options' => [
                        'class' => 'nav_menu',
                    ],
                ]);
                echo '<div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>';
                echo Nav::widget([
                    'options' => ['class' => 'nav navbar-nav navbar-right'],
                    'items' => [
                       Yii::$app->user->isGuest ?
                            ['label' => 'Login', 'url' => ['/site/login']] :
                            [
                                'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                                'url' => ['/site/logout'],
                                'linkOptions' => ['data-method' => 'post']
                            ],




                    ],



                    //'options' => ['class' => 'navbar-nav'],
                ]);
                NavBar::end();
            ?>
            
        </div>



        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <?php if (isset($this->params['h1'])): ?>
                <div class="page-title">
                    <div class="title_left">
                        <h1><?= $this->params['h1'] ?></h1>
                    </div>
                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="clearfix"></div>

            <?= $content ?>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
            <div class="pull-right">
                <a href="https://"" rel="nofollow" target="_blank">Betamasano</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>

</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>