controllers/RoleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Role;
use app\models\RoleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


/**
 * RoleController implements the CRUD actions for Role model.
 */
class RoleController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['roleIndex'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['roleView'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['roleCreate'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update'],
                        'roles' => ['roleUpdate'],
                    ],
                    
                ],
            ],
        ];
    }


    /**
     * Lists all Role models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Role model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Role model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Role();

        if ($model->load(Yii::$app->request->post()) ) {
            $model->createdBy = Yii::$app->user->identity->id;
            if ($model->save())
                return $this->redirect(['view', 'id' => $model->id]);
        } 
            return $this->render('create', [
                'model' => $model,
            ]);
        
    }

    /**
     * Updates an existing Role model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Finds the Role model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Role the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Role::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserService;
use app\models\UserSearch;
use app\models\UserDetails;
use app\models\Educations;
use app\models\Qualifications;
use app\models\Companies;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\libraries\Encryption;
use yii\filters\AccessControl;
use \yii\web\UploadedFile;

use yii\helpers\Url;


/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['userIndex'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['view'],
                        'roles' => ['userView'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['userCreate'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update'],
                        'roles' => ['userUpdate'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['change-password'],
                        'roles' => ['userChangePassword'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reset-account'],
                        'roles' => ['userResetAccount'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['account'],
                        'roles' => ['userAccount'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['download'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }



    public function actionChangePassword() {
        $model = $this->findModel(Yii::$app->user->id);
        
        if ($model->load(Yii::$app->request->post())) {
            $model->current_password = $_POST['User']['current_password'];
            $model->scenario = User::SCENARIO_CHANGEPASSWORD;
            if ($model->validate()) {
                if ($model->validatePassword($model->current_password, 
                        Yii::$app->user->identity->password, 
                        Yii::$app->user->identity->salt)) {
                    $user = User::findOne(Yii::$app->user->identity->id); 
                    if ($user) {
                        $user->salt = Encryption::generateSalt();  
                        $user->password =  Encryption::encrypt($model->password, $user->salt);
                        if ($user->update(false)) {
                            Yii::$app->user->logout();
        		    return $this->goHome();
                        }
                    } 
                } else {
                    
                    $model->addError("current_password", 
                            "You have entered an incorrect current password");
                }
            }
        }
        $model->current_password = "";
        $model->password = "";
        $model->repeat_password = "";
        return $this->render('change-password', [
                    'model' => $model,
        ]);
    }


    /*public function actionResetAccount($id) {
        $model = $this->findModel($id);
        $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
        if ($model->update()) {
            $content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                    . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td><a href=" 
                    . Url::toRoute(['site/reset', 'username' => $model->username, 
                    'key' => $model->activation_key], true) 
                    . ">Click here to activate your account</a></td></tr></table>" 
                    . "<p>This email is  auto-generated by Betamasano system. Do not reply.</p>";
            Yii::$app->mailer->compose('template', [
                        'content' => $content
                    ]) // a view rendering result becomes the message body here
                    ->setFrom(Yii::$app->params['sent_from'])
                    ->setTo($model->email)
                    ->setSubject('Credentials - Betamasano')
                    ->send();
            Yii::$app->session->setFlash('info', 'User Account reset succcess. A link has been sent to the users email');        
        
        } else {
            Yii::$app->session->setFlash('error', 'Error resetting user account');
        }
        return $this->redirect(['user/index']);
    }*/

    public function actionResetAccount($id) {
        $model = $this->findModel($id);
    
        if ($model->load(Yii::$app->request->post()) ) {
 
            $model->modified_by = Yii::$app->user->identity->id;
            $model->salt = Encryption::generateSalt();
            $model->status_id = User::STATUS_ACTIVE;
            $model->scenario = User::SCENARIO_RESET;
            if ($model->validate()) {
                $password = $model->password;
                $model->password = Encryption::encrypt($model->password, $model->salt);
                $model->repeat_password = $model->password;
                $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
                
                if ($model->save()) {
                    
                    /*
                    //Send EMail with credentials
                    $content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                                . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td><a href=" 
				. Url::toRoute(['site/activate', 'email' => $model->email, 'key' => $model->activation_key], true) 
				. ">Click here to activate your account</a></td></tr></table>" 
				. "<p>username : " . $model->username . "</p>"
                                . "<p>password : " . $password . "</p>"
                                . "<p>This email is  auto-generated by Betamasano system. Do not reply.</p>";
                    	    Yii::$app->mailer->compose('template', [
                                'content' => $content
                            ]) // a view rendering result becomes the message body here
                            ->setFrom(Yii::$app->params['sent_from'])
                            ->setTo($model->email)
                            ->setSubject('Credentials - Betamasano')
                            ->send();*/
                    Yii::$app->session->setFlash('info', 'Password has been changed. An email has been sent to the account with the new information');        
                   
                    
                }
            }
        }
        $model->password = "";
        $model->repeat_password = "";
        return $this->render('reset', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new User();
    
        if ($model->load(Yii::$app->request->post()) ) {

            $model->created_by = Yii::$app->user->identity->id;
            $model->salt = Encryption::generateSalt();
            $model->status_id = User::STATUS_ACTIVE;
            $model->scenario = User::SCENARIO_CREATE;

            if ($model->validate()) {
                $password = $model->password;
                $model->password = Encryption::encrypt($model->password, $model->salt);
                $model->repeat_password = $model->password;
                $model->activation_key = Encryption::encrypt(microtime() . $model->password, $model->salt);
                $model->msisdn = "254" . substr($model->msisdn, -9);
                if ($model->save()) {
                    
                    
                    $auth = Yii::$app->authManager;
                    switch ($model->role_id) {
                        case 1:
                            $role =  $auth->getRole('super_admin');
                        break;
                        case 2:
                            $role =  $auth->getRole('ccr');
                        break;
                    }
                        
                    $auth->assign($role, $model->getId()); 
                        
                    //Send EMail with credentials
                    /*$content = "<p>Hello " . $model->firstname . " " . $model->lastname  . ", <p>"
                                . "<table class='btn-primary' cellpadding='0' cellspacing='0' border='0'><tr><td>
                                     <a href=" . Url::toRoute(['site/activate', 'email' => $model->email, 
                                'key' => $model->activation_key], true) . ">Click here to activate your account</a></td>
                                </tr></table>" 
                            . "<p>username : " . $model->username . "</p>"
                            . "<p>password : " . $password . "</p>"
                            . "<p>This email is  auto-generated by DASSO system. Do not reply.</p>";

views/user/_changePassword.php
<?php

use kartik\helpers\Html;
use kartik\builder\Form;
use kartik\widgets\ActiveForm;
use \yiister\gentelella\widgets\Panel;
/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="row">
    <div class="col-md-12 col-xs-12">

<?php
Panel::begin(['header' => "Change Password",]);?>
<div id="system-messages" style="opacity: 1; display: none"></div>
<?php

<?php
$form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL, 'fullSpan' => 10, 'formConfig'=>['labelSpan'=>2,  'deviceSize' => ActiveForm::SIZE_SMALL]]);
$content =  Form::widget([
   'model'=>$model,
    'form'=>$form,
    'columns'=>1,
     'attributeDefaults'=>[
        'type'=>Form::INPUT_TEXT,
        'labelOptions'=>['class'=>'col-md-3'], 
        'inputContainer'=>['class'=>'col-md-9'], 
        'container'=>['class'=>'form-group'],
    ],
    'attributes'=>[
        'currentPassword' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Enter Cuurent Password']
        ],
        'password' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Enter New Password']
        ],
        'repeatPassword' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Confirm Password']
        ],
        'actions'=>[
            'type'=>Form::INPUT_RAW, 
            'value'=>'<div style="text-align: right; margin-top: 20px">' . 
                Html::submitButton('Change Password', ['class'=>'btn btn-primary']) . 
                '</div>'
        ],
    ]
]);
ActiveForm::end();
 Panel::end();
?>
</<div id="system-messages" style="opacity: 1; display: none"></div>
</div>

views/user/_form.php
<?php

use kartik\helpers\Html;
use kartik\builder\Form;
//use yii\widgets\ActiveForm;
use kartik\widgets\ActiveForm;
use \yiister\gentelella\widgets\Panel;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="row">
    <div class="col-md-12 col-xs-12">

<?php
Panel::begin(['header' => "New User",]);
$form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL, 'fullSpan' => 10, 'formConfig'=>['labelSpan'=>2,  'deviceSize' => ActiveForm::SIZE_SMALL]]);
echo  Form::widget([
   'model'=>$model,
    'form'=>$form,
    'columns'=>1,
     'attributeDefaults'=>[
        'type'=>Form::INPUT_TEXT,
        'labelOptions'=>['class'=>'col-md-3'], 
        'inputContainer'=>['class'=>'col-md-9'], 
        'container'=>['class'=>'form-group'],
    ],
    'attributes'=>[
        'role_id' => [
            'type' => Form::INPUT_DROPDOWN_LIST, 
            'items'=>$model->getRoleList(),
            'options' => ['prompt' => 'Select Role ..']
        ],
        'firstname' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'First Name']
        ],
        'lastname' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Last Name']
        ],
        'username' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Username']
        ],
        'password' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Enter Password']
        ],
        'repeat_password' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Confirm Password']
        ],
        'email' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Email Address e.g 123@me.co.ke']
        ],
        'msisdn' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Mobile No.']
        ],
       'actions'=>[
            'type'=>Form::INPUT_RAW, 
            'value'=>'<div style="text-align: right; margin-top: 20px">' . 
                Html::submitButton('Create', ['class'=>'btn btn-primary']) . 
                '</div>'
        ],
    ]
]);
ActiveForm::end();
 Panel::end();
?>
</div>
</div>

views/user/_formold.php
<?php

use kartik\helpers\Html;
use kartik\builder\Form;
//use yii\widgets\ActiveForm;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL, 'fullSpan' => 10, 'formConfig'=>['labelSpan'=>2,  'deviceSize' => ActiveForm::SIZE_SMALL]]);

$content =  Form::widget([
   'model'=>$model,
    'form'=>$form,
    'columns'=>1,
     'attributeDefaults'=>[
        'type'=>Form::INPUT_TEXT,
        'labelOptions'=>['class'=>'col-md-3'], 
        'inputContainer'=>['class'=>'col-md-9'], 
        'container'=>['class'=>'form-group'],
    ],
    'attributes'=>[
        
        'first_name' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'First Name']
        ],
        'last_name' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Last Name']
        ],
        'username' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Username']
        ],
        'password' => [
            'type' => Form::INPUT_PASSWORD , 
            'options' => ['placeholder' => 'Enter Password']
        ],
        'email' => [
            'type' => Form::INPUT_TEXT, 
            'options' => ['placeholder' => 'Email Address e.g 123@me.co.ke']
        ],
       'actions'=>[
            'type'=>Form::INPUT_RAW, 
            'value'=>'<div style="text-align: right; margin-top: 20px">' . 
                Html::submitButton('Create', ['class'=>'btn btn-primary']) . 
                '</div>'
        ],
        'actions'=>[
            'type'=>Form::INPUT_RAW, 
            'value'=>'<div style="text-align: right; margin-top: 20px">' . 
                Html::resetButton('Reset', ['class'=>'btn btn-default']) . ' ' .
                Html::submitButton('Update', ['type'=>'button', 'class'=>'btn btn-primary']) . 
                '</div>'
        ],
    ]
]);

echo Html::panel(
    ['heading' => $this->title, 'body' => '<div class="panel-body">' . $content . '</div>'],
    Html::TYPE_PRIMARY
);

echo Html::endForm();
ActiveForm::end();

views/user/_search.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use kartik\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearchSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
                'formConfig' => ['labelSpan' => 4, 'deviceSize' => ActiveForm::SIZE_SMALL],
                'type' => ActiveForm::TYPE_HORIZONTAL,
    ]);
    ?>
    
    <div class="form-group kv-fieldset-inline">

        <?=
        Html::activeLabel($model, 'roleId', [
            'label' => 'Role',
            'class' => 'col-sm-3 control-label'
        ])
        ?>
        <div class="col-sm-3">     
            <?= $form->field($model, 'roleId', ['showLabels' => false])->dropDownList($model->getRoleList(),  ['prompt'=>'Select Role']) ?>
        </div>  
     </div>
    <div class="form-group kv-fieldset-inline">
        <?=
        Html::activeLabel($model, 'username', [
            'label' => 'Username',
            'class' => 'col-sm-3 control-label'
        ])
        ?>
         <div class="col-sm-3">
            <?= $form->field($model, 'username', ['showLabels' => false]) ?>
        </div>  
        <?=
        Html::activeLabel($model, 'email', [
            'label' => 'Email',
            'class' => 'col-sm-3 control-label'
        ])
        ?>
        <div class="col-sm-3">     
            <?= $form->field($model, 'email', ['showLabels' => false]) ?>
        </div>  
     </div>

    <?php // $form->field($model, 'id') ?>

    <?php // $form->field($model, 'clientId') ?>

    <?php // $form->field($model, 'roleId') ?>

    <?php // $form->field($model, 'username') ?>

    <?php // $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'msisdn') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'salt') ?>

    <?php // echo $form->field($model, 'activationKey') ?>

    <?php // echo $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'dateCreated') ?>

    <?php // echo $form->field($model, 'createdBy') ?>

    <?php // echo $form->field($model, 'dateModified') ?>

    <?php // echo $form->field($model, 'modifiedBy') ?>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
            <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
            <?php //Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
        </div>
    </div> 

    <?php ActiveForm::end(); ?>

</div>

views/user/change-password.php
<?php

use yii\helpers\Url;
use kartik\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;
use kartik\widgets\DepDrop;
use kartik\helpers\Html;
use kartik\builder\Form;
use \yiister\gentelella\widgets\Panel;

$this->title = 'Company Profile';
/* @var $this yii\web\View */
/* @var $model app\models\ScheduleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<?= \yiister\gentelella\widgets\FlashAlert::widget(['showHeader' => true]) ?>

<div class="row">
    <div class="col-md-12 col-xs-12">

<?php
Panel::begin();
$form = ActiveForm::begin(['type' => ActiveForm::TYPE_HORIZONTAL, 
    'fullSpan' => 10, 'formConfig' => ['labelSpan' => 2, 'deviceSize' => ActiveForm::SIZE_SMALL], 'options' => ['enctype' => 'multipart/form-data']]);


Panel::begin(['header' => "Change Password",]);
 echo Form::widget([
        'model' => $model,
        'form' => $form,
        'columns' => 1,
        'attributes' => [
           'username' => [
                'type' => Form::INPUT_STATIC, 
                'options' => ['placeholder' => 'Username']
            ],
            'current_password' => [
                'type' => Form::INPUT_PASSWORD, 
                'options' => ['placeholder' => 'Current Password']
            ],
            'password' => [
                'type' => Form::INPUT_PASSWORD, 
                'options' => ['placeholder' => 'Password']
            ],
            'repeat_password' => [
                'type' => Form::INPUT_PASSWORD, 
                'options' => ['placeholder' => 'Repeat Password'],
                'hint' => 'To change the current user password, enter the new password in both fields.'
            ],
            'actions' => [
                'type' => Form::INPUT_RAW,
                'value' => Html::submitButton('Change Password', ['class' => 'btn btn-primary'])
            ],
       ],
    ]);   
Panel::end();

ActiveForm::end();
 Panel::end();
?>
</div>
</div>

views/user/changePassword.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['changePassword']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <?= $this->render('_changePassword', [
        'model' => $model,
    ]) ?>

</div>

views/user/complete.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use \yiister\gentelella\widgets\Panel;

$this->title = 'Registration Complete';

 \yiister\gentelella\widgets\FlashAlert::widget(['showHeader' => true]);

 ?>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <?php
        Panel::begin();
        Panel::begin(['header' => 'Personal Details',]);
        echo DetailView::widget([
            'model' => $individual,
            'attributes' => [
                'salutationName',
                'first_name',
                'last_name',
                'genderValue',
                'date_of_birth',
                'id_number',
                'phone_number',
                'volunteer',
                'wardName',
                [
                    'attribute'=>'curriculum_vitae',
                    'format'=>'raw',
                    'value'=>Html::a($individual->curriculum_vitae, ['user/download', 'filename' => $individual->curriculum_vitae]),
                ],
            ]
        ]);
        Panel::end();

        foreach ($education as $edu) {

            Panel::begin(['header' => 'Education Details',]);
            echo DetailView::widget([
                'model' => $edu,
                'attributes' => [
                    'DegreeLevelName',
                    'courseName',
                ]
            ]);
            Panel::end();
        }

        foreach ($qualification as $qua) {

            Panel::begin(['header' => 'Qualification Details']);
            echo DetailView::widget([
                'model' => $qua,
                'attributes' => [
                    //'sectorName',
                    'organisation_name',
                    'job_title',
                    'years_experience',
                ]
            ]);
            Panel::end();
        }

/*[
                'attribute'=>'upload',
                'format'=>'raw',
                'value'=>Html::a($project->upload, ['project/download', 'fileName' => $project->upload]),
            ],*/
        Panel::end();
        ?>
</div>
</div>

views/user/completed.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use \yiister\gentelella\widgets\Panel;

$this->title = 'Registration Complete';
?>
 
 <?= \yiister\gentelella\widgets\FlashAlert::widget(['showHeader' => true]);?>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <?php
        Panel::begin();
        Panel::begin(['header' => 'Personal Details',]);
        echo DetailView::widget([
            'model' => $individual,
            'attributes' => [
                'salutationName',
                'first_name',
                'last_name',
                'genderValue',
                'date_of_birth',
                'id_number',
                'phone_number',
                'volunteer',
                'wardName',
                [
                    'label' => 'Company Profile',
                    'attribute'=>'curriculum_vitae',
                    'format'=>'raw',
                    'value'=>Html::a($individual->curriculum_vitae, ['user/download', 'filename' => $individual->curriculum_vitae]),
                ],
            ]
        ]);
        Panel::end();
        Panel::begin(['header' => 'Company Details',]);
            echo DetailView::widget([
                'model' => $company,
                'attributes' => [
                    'sectorName',
                    'company_name',
                    'phone_number',
                    'address',
                    'postal_code',
                    'city',
                    'countyName',
                    'email',
                    'domain',
                ]
            ]);
        Panel::end();    
        

/*[
                'attribute'=>'upload',
                'format'=>'raw',
                'value'=>Html::a($project->upload, ['project/download', 'fileName' => $project->upload]),
            ],*/
        Panel::end();
        ?>
</div>
</div>

views/user/index.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use \yiister\gentelella\widgets\Panel;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearchSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12 col-xs-12">
    <?php Panel::begin();?>

<?= \yiister\gentelella\widgets\FlashAlert::widget(['showHeader' => true]) ?>
    <?= \yiister\gentelella\widgets\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [ 
                'attribute' => 'role_id',
                'label' => 'Role',
                'format' => 'text',
                'content' => function($data) {
                    return $data->getRoleName();
                }
            ],
            'username',
            'email:email',
            'msisdn',
            [ 
                'attribute' => 'status_id',
                'label' => 'Status',
                'format' => 'text',
                'content' => function($data) {
                    return $data->getStatusName();
                }
            ],        
                    
            'date_created',
            // 'createdBy',
            [ 
                'attribute' => 'created_by',
                'label' => 'Created By',
                'format' => 'text',
                'content' => function($data) {
                    return $data->getCreatedBy();
                }
            ],
            // 'dateModified',
            // 'modifiedBy',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                'buttons' => [
                    'reset' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-refresh"></span>', $url, [
                                    'title' => Yii::t('app', 'Reset PIN'),                            
                        ]);
                    }
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'reset') {
                        return  Url::to(['user/reset-account', 'id' => $model['id']]);
                    } else if ($action === 'update') {
	                    return Url::to(['user/update', 'id' => $model['id']]);
		            }
                }
            ],
        ],
    ]); ?>

 <?php Panel::end() ?>
</div>
</div>