models/Agent.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "agent".
 *
 * @property int $id
 * @property string $agent_code
 * @property string $msisdn
 * @property string $agent_name
 * @property int $status
 * @property string $password
 * @property string $salt
 * @property int $password_tries
 * @property string $date_created
 * @property int $created_by
 * @property string $date_modified
 */
class Agent extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'agent';
    }


    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['date_created', 'date_modified'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'date_modified',
                ],
                'value' => new Expression('NOW()'),
            ],
             'bedezign\yii2\audit\AuditTrailBehavior'
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'password_tries', 'created_by'], 'integer'],
            [['password', 'salt'], 'string'],
            [['date_created', 'date_modified'], 'safe'],
            [['agent_code'], 'string', 'max' => 20],
            [['msisdn'], 'string', 'max' => 12],
            [['agent_name'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'agent_code' => 'Agent Code',
            'msisdn' => 'Msisdn',
            'agent_name' => 'Agent Name',
            'status' => 'Status',
            'password' => 'Password',
            'salt' => 'Salt',
            'password_tries' => 'Password Tries',
            'date_created' => 'Date Created',
            'created_by' => 'Created By',
            'date_modified' => 'Date Modified',
        ];
    }
}

controllers/AgentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Agent;
use app\models\AgentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\libraries\Encryption;
use yii\filters\AccessControl;
/**
 * AgentController implements the CRUD actions for Agent model.
 */
class AgentController extends Controller
{
    /**
     * {@inheritdoc}
     */
     public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['agentIndex'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reset-pin'],
                        'roles' => ['agentResetPin'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Agent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AgentSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionResetPin($id) {
        $model = $this->findModel($id);
        $password = rand(1000, 9999);

            
        $model->salt = Encryption::generateSalt();
        $model->status = 3;
        if ($model->validate()) {
   
            $model->password = Encryption::encrypt($password, $model->salt);
            
            if ($model->save()) {
         
                 $sql = "INSERT INTO dbqueue (Originator, Destination, Message, SMSCID, MessageDirection) 
                            VALUES ('" . Yii::$app->params['originator'] . "', '" 
                            . $model->msisdn . "', '" . sprintf(Yii::$app->params['message'], $model->agent_name, $password) . "', 'SAFCOMKE', 'OUT')";
                \Yii::$app->db->createCommand($sql)->execute();
                Yii::$app->session->setFlash('info', 'Password has been changed. SMS has been sent to the agents number with their one time PIN');        
               
                
            }
        }
        $model->password = "";
        return $this->render('view', [
            'model' => $model,
        ]);
    }


    /**
     * Finds the Agent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Agent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Agent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/agent/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Agent */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="agent-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'agent_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'msisdn')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'agent_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'password')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'salt')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'password_tries')->textInput() ?>

    <?= $form->field($model, 'date_created')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'date_modified')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/agent/_search.php
<?php

use kartik\widgets\ActiveForm;
use kartik\widgets\DatePicker;
use kartik\widgets\DateTimePicker;
use kartik\helpers\Html;
use kartik\builder\Form;


/* @var $this yii\web\View */
/* @var $model app\models\ScheduleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$form = ActiveForm::begin(['type'=>ActiveForm::TYPE_VERTICAL, 'method' => 'get', 'fullSpan' => 11, 'formConfig'=>['labelSpan'=>4,  'deviceSize' => ActiveForm::SIZE_SMALL]]);
echo Form::widget([ // fields with labels
    'model'=>$model,
    'form'=>$form,
    'columns'=>2,
    'attributes'=>[
        'msisdn'=>[
            'label'=>'Mobile No.', 
            'options'=>['placeholder'=>'Mobile No.'],
            'type' => Form::INPUT_TEXT

        ],
        /*'name'=>['label'=>'Customer Name', 
            'options'=>['placeholder'=>'Customer Name'],
            'type' => Form::INPUT_TEXT],
        */
        
        
       
    ]
]);

echo '<div class="text-right">' . Html::submitButton('Search', ['class'=>'btn btn-default']) . '</div>';


ActiveForm::end();

?>

views/agent/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Agent */

$this->title = 'Create Agent';
$this->params['breadcrumbs'][] = ['label' => 'Agents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="agent-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/agent/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use \yiister\gentelella\widgets\Panel;
use kartik\export\ExportMenu;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CustomerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Agents';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12 col-xs-12">
<?php Panel::begin(['header' => "Agent Information",]);?>

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'agent_code',
            'msisdn',
            'agent_name',
            'status',
            //'password:ntext',
            //'salt:ntext',
            //'password_tries',
            'date_created',
            'created_by',
            'date_modified',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{reset}',
                'buttons' => [
                    'reset' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-refresh"></span>', $url, [
                                    'title' => Yii::t('app', 'Reset PIN'),                            
                        ]);
                    }
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'reset') {
                        return  Url::to(['agent/reset-pin', 'id' => $model['id']]);
                    }
                }
            ],
        ],
    ]); ?>

 <?php Panel::end() ?>
</div>
</div>

views/agent/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Agent */

$this->title = 'Update Agent: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Agents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="agent-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/agent/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use \yiister\gentelella\widgets\Panel;

/* @var $this yii\web\View */
/* @var $model app\models\Agent */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Agents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="agent-view">

    <?php
        Panel::begin(['header' => "Agent ID : " . $this->title,]);?>

    <?= \yiister\gentelella\widgets\FlashAlert::widget(['showHeader' => true]) ?>    
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'agent_code',
            'msisdn',
            'agent_name',
            //'status',
            //'password:ntext',
            //'salt:ntext',
            //'password_tries',
            'date_created',
            //'created_by',
            //'date_modified',
        ],
    ]) ?>


 <?php Panel::end();
?>
</div>